export const JobDescriptionPrompt =
  "Based on the job description provided, identify relevant keywords and phrases for the ATS. Include specific keywords that are used more than once and technical words. Then, create a list. Do not indicate any explanation, we would like just the list of optimized words. There should be at least 20 words included in the response. Priorize them by needed skills for the role. It will be in format of a list of only those words and seperated by a comma.";

export const createCuratedResumePrompt = (keywords) => {
  return `I'm going to give you a list of keywords and I will input the data from my generic resume and a job description. What I want you to do is create a curated skills section for me targeting these keywords. Also I want you to create a new professional summary based on these keywords. The professional summary should be under 400 charactors long. If there is any keywords not listed in the resume then place those in a seperate list on the bottom. The summary must have the exact same content; please do not hallucinate just to add keywords. Feel free to make a new professional summary including one of the achivements or metrics <keywords to target> ${keywords} <current summary and accomplishments> ${CurrentResumePrompt}`;
};

export const SummaryAndAccomplishments =
  "<current summary>An experienced React Native Developer with 5 years Engineering Experience, I've led a team of 4 developers for the Levi Strauss mobile application. We increased committed project delivery by 38% within the deadline in a cross-functional, dynamic agile environment. Leveraging my problem-solving aptitude, I boosted the application's performance by ~600% on lower-end Android devices. I also boosted product conversion by 112% through a complete redesign of product navigation. \n<Accomplishments>: \n • Accomplished a 112% increase in Product Conversion with a redesign of Product Navigation. \n • Improved performance by ~600% and resolved crashes on lower Android devices through bridge code, pagination, and multitasking.\n• Led a team of 4 developers and boosted the Agile project completion rate by 38%. • Implemented the first Clean Architecture Domain layer in the app, reducing testing errors by 45% and increasing test coverage by 20%. \n • Improved CSAT from 64% to 74% in terms of ease of navigation. ";

export const CurrentResumePrompt =
  "John Jackson \n Flat Rock, MI • 3133160160 • johngjackson0@gmail.com • linkedin.com/in/jgj0/ \n React Native Developer \n An experienced React Native Developer with 5 years Engineering Experience, I've led a team of 4 developers for the Levi Strauss mobile application. We increased committed project delivery by 38% within the deadline in a cross-functional, dynamic agile environment. Leveraging my problem-solving aptitude, I boosted the application's performance by ~600% on lower-end Android devices. I also boosted product conversion by 112% through a complete redesign of product navigation. \n WORK EXPERIENCE \n Launch by NTT Data • Full-time 01/2022 - Present React Native Developer \n • Accomplished a 112% increase in Product Conversion with a redesign of Product Navigation. \n • Improved performance by ~600% and resolved crashes on lower Android devices through bridge code, pagination, and multitasking.\n• Led a team of 4 developers and boosted the Agile project completion rate by 38%. • Implemented the first Clean Architecture Domain layer in the app, reducing testing errors by 45% and increasing test coverage by 20%. \n • Improved CSAT from 64% to 74% in terms of ease of navigation. \n\n Tanagr Software 01/2018 - 12/2022 Founder \n • Write & Publish multiple React Native & Flutter mobile applications to the Google Play and Apple Stores \n • Implement a Clean Architecture login template complete with AWS microservices, 100%-unit test coverage and infrastructure as code \n • Executed a refined coding strategy and clean architecture, specifically engineered to streamline the unit testing process and bolster testing efficiency. \n\n EDUCATION \n Bachelor Of Science in Computer Science Baker University \n• Flint, MI, USA \n• GPA: +3.7 \n SKILLS \n Mobile Apps, TypeScript, Ability to Collaborate in Cross Functional Teams, Empathy, Innovation, Localization, Takes Ownership, Troubleshooting, Software Engineering, Pair Programming, GraphQl Data Fetching and Mutations, Scale Software Solutions, Takes Initiative, Mobile App development, Code Review, Creates Apps From The Ground Up, Compassion, Cross Platform, Open Knowledge Sharing, Collaborative Design";
